server:
    port: 8080
    contextPath: /

spring:
    application:
        name: cloud-client
    port: 8080

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka
